version: "3.8"
services:
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
    # command: ["sh", "-c", "npx prisma migrate deploy && node build"]
    environment:
      - PORT=5173
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/saasdb
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - saasnetwork

  db:
    container_name: pg_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saasdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - saasnetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


networks:
  saasnetwork:
    driver: bridge
