version: "3.8"
services:
  frontend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
    command: npm run dev
    environment:
      - PORT=5173
      - HOST=0.0.0.0
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: pg_db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saasdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:
